Minor changes to sync-related Actions workflows (#135)

diff --git a/.github/workflows/open-public-sync-pr.yml b/.github/workflows/open-public-sync-pr.yml
--- a/.github/workflows/open-public-sync-pr.yml
+++ b/.github/workflows/open-public-sync-pr.yml
@@ -20,7 +20,7 @@ jobs:
           uses: actions/checkout@v4
           with:
             # this token should be a fine-grained PAT with write permissions
-            # for repository contents, pull-requests, and workflows
+            # for repository "contents", "pull-requests", and "workflows"
             # note: a PAT is needed to allow the action to push the sync branch to the private repo;
             # it is not sufficient to grant `permissions: write-all` to the default GITHUB_TOKEN
             # (see https://github.com/orgs/community/discussions/35410)
@@ -34,37 +34,36 @@ jobs:
             git remote add ${{ env.PUBLIC_REPO_REMOTE }} ${{ env.PUBLIC_REPO_URL }}
             git fetch --all
 
-        - name: Check for new commits and exit if there are none
+        - name: Check for new commits in the public repo and exit if there are none
           run: |
             NEW_COMMITS=$(git log --oneline --no-merges origin/main..${{ env.PUBLIC_REPO_REMOTE }}/main)
             if [ -z "$NEW_COMMITS" ]; then
-                echo "There are no new commits in the public repo; no PR will be opened."
+                echo "There are no new commits in the public repo, so no PR will be opened."
                 exit 1
             fi
 
         - name: Delete the sync branch if it exists
+          # note: if the sync branch already exists and there is an open PR associated with it,
+          # this will automatically close the PR
           run: |
-            # TODO (KC): if the sync branch already exists, should we check if there is already
-            # an open PR associated with it? (this will happen if the action is run twice in a row)
-            # if we don't, and there is an open PR, deleting the branch will automatically close it
             git branch -D ${{ env.SYNC_BRANCH }} || true
-            git push --force origin --delete ${{ env.SYNC_BRANCH }} || true
+            git push --force --delete origin ${{ env.SYNC_BRANCH }} || true
 
-        - name: Create and push the sync branch
+        - name: Create and push the sync branch to the private repo
+          # we use `git branch` here instead of `git checkout` followed by `git pull public main`
+          # because the latter will fail if there are merge conflicts
           run: |
             git branch ${{ env.SYNC_BRANCH }} ${{ env.PUBLIC_REPO_REMOTE }}/main
             git branch --unset-upstream ${{ env.SYNC_BRANCH }}
             git push origin ${{ env.SYNC_BRANCH }}
 
-        - name: Open a PR
+        - name: Open a PR to merge the sync branch into the private repo's main branch
           env:
             GH_TOKEN: ${{ secrets.OPEN_PUBLIC_SYNC_PR_PAT }}
             PR_BODY: >
                 This PR adds new contributions made to the public repo
                 in order to keep the private repo up to date with the public repo.
-
-                It was automatically generated by the
-                [open-public-sync-pr](./.github/workflows/open-public-sync-pr.yml)
+                It was automatically generated by the "open-public-sync-pr"
                 GitHub Actions workflow.
           run: |
             gh pr create \
